// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using population.Model;
using System;

namespace population.Migrations
{
    [DbContext(typeof(PopulationContext))]
    [Migration("20180802035925_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("population.Model.Actual", b =>
                {
                    b.Property<int>("State")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActualHouseholds");

                    b.Property<int>("ActualPopulation");

                    b.HasKey("State");

                    b.ToTable("Actuals");
                });

            modelBuilder.Entity("population.Model.Estimate", b =>
                {
                    b.Property<int>("State");

                    b.Property<int>("Districts");

                    b.Property<int>("EstimateHoseholds");

                    b.Property<int>("EstimatesPopulation");

                    b.HasKey("State", "Districts");

                    b.HasAlternateKey("Districts", "State");

                    b.ToTable("Estimates");
                });
#pragma warning restore 612, 618
        }
    }
}
